apiVersion: v1
kind: ServiceAccount
metadata:
  name: invadium-backend-sa
  namespace: invadium
  labels:
    app.kubernetes.io/part-of: invadium
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: invadium-backend-sa
  namespace: invadium
  labels:
    app.kubernetes.io/part-of: invadium
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: invadium-backend-sa
  namespace: invadium
  labels:
    app.kubernetes.io/part-of: invadium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: invadium-backend-sa
subjects:
  - kind: ServiceAccount
    name: invadium-backend-sa
    namespace: invadium
