apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invadium-pvc
  namespace: invadium
  labels:
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: invadium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
