[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    'challenges/=challenges/',
    'internals/=internals/',
    'src/=src/'
]

[rpc_endpoints]
localhost = "${LOCALHOST}"
goerli = "${GOERLI_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config