php-settings:
    # Path to PHP executable
    PHPPath : C:/PHP/php.exe
       
    # PHP file extensions
    PHPExts : 
      - .php 
      - .php3 
      - .php4
      - .php5 
      - .phtml 
      - .inc
       
    # Path to PHP parse project (Main.php file)
    PHPParsePath : D:\Dokumenter\Skolesager\10.-Semester\GIT\PHPAnalysis\PHPAnalysis-parser\src\Main.php

graph-settings:
    # Path to the graphviz dot convert tool
    GraphvizPath : C:\Program Files (x86)\Graphviz-2.38\dot.exe
    
    # Arguments to the graphviz
    GraphvizArguments : -Tpng -O

component-settings:
    # Indicates whether external components should be used
    IncludeComponents : True
    
    # Path to external components. 
    ComponentFolder : .\Components\

func-spec-settings:
    #Path array to function specifications
    PHPSpecs:
      - "C:/mmk-php-vuln-scanner/PHPAnalysis/PHPAnalysis/FunctionSpecs/JSONSpecifications"
      - "C:/mmk-php-vuln-scanner/PHPAnalysis/PHPAnalysis/FunctionSpecs/StoredSQLProviders"

    #Path to extensions specification, can be excluded if not needed
    ExtensionSpecs:
      - "C:/mmk-php-vuln-scanner/PHPAnalysis/PHPAnalysis/FunctionSpecs/WPSpecifications"    