#!/bin/bash
set -e
set -u
if ! [ -x /usr/bin/docker-compose ]; then
    echo Install docker-compose
    curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
    chmod +x /usr/bin/docker-compose
fi
