#!/bin/bash
set -u
INTERVAL=20
CHECK=1
CHECKS_NUM=3
URL="http://0.0.0.0:8081/login.php"
while [ ${CHECK} -le ${CHECKS_NUM} ]; do
  CLI_HEALTH_CHECK=$(curl -w "%{http_code}" -o /dev/null -s ${URL})
  if [ ${CLI_HEALTH_CHECK} -eq 200 ]; then
    echo "OK"
    exit 0
  else
    echo "NOK"
    if [ ${CHECK} -eq ${CHECKS_NUM} ]; then
        exit 1
    fi
    let "CHECK=${CHECK} + 1"
    echo "Waiting ${INTERVAL}s..."
    sleep ${INTERVAL}
 fi
done
exit 1