apiVersion: v1
kind: Service
metadata:
  name: invadium-frontend
  namespace: invadium
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: invadium
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: invadium
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invadium-frontend
  namespace: invadium
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: invadium
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: invadium
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: invadium
    spec:
      containers:
        - name: invadium
          image: invadium-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
          readinessProbe:
            timeoutSeconds: 5
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: 3000
          env:
            - name: NEXT_BACKEND_API_URL
              valueFrom:
                configMapKeyRef:
                  name: invadium-config
                  key: INVADIUM_API_ROOT
