id: nmap
name: Nmap
desc: |
  Nmap ("Network Mapper") is a free and open source utility
  for network discovery and security auditing.
image: ghcr.io/dynatrace-oss/invadium-nmap
env:
  - name: TARGET
    value: scanme.nmap.org
    desc: Target address to scan
tags:
  - recon
  - network-scanner
links:
  - https://nmap.org/
  - https://github.com/nmap/nmap
steps:
  nmap_scan:
    name: Standard scan
    desc: Scans all reserved TCP ports on the target
    commands:
      - nmap -T$TIMING $OPTIONS $TARGET
    env:
      - name: TIMING
        value: 5
        desc: Timing template between 0 - 5 (higher is faster)
      - name: OPTIONS
        desc: Additional options for nmap
  nmap_stealthy_scan:
    name: Stealthy SYN scan
    desc: Does a stealthy scan and tries to guess the operating system of the target
    commands:
      - nmap -sS -O $OPTIONS $TARGET
    env:
      - name: OPTIONS
        desc: Additional options for nmap
  nmap_webserver_scan:
    name: Scan for webservers
    desc: Scans for webservers on a subnet without pinging them
    commands:
      - nmap -Pn -p$PORT $OPTIONS $TARGET/$SUBNET
    env:
      - name: PORT
        value: 80
        desc: Webserver port
      - name: SUBNET
        value: 24
        desc: Subnet prefix
      - name: OPTIONS
        desc: Additional options for nmap
