id: sqlmap
name: sqlmap
desc: |
  sqlmap is an open source penetration testing tool that automates the process of
  detecting and exploiting SQL injection flaws and taking over of database servers.
image: ghcr.io/dynatrace-oss/invadium-sqlmap
env:
  - name: URL
    value: "http://127.0.0.1/vuln.php?id=1"
    desc: Vulnerable target URL used for sqlmap
tags:
  - recon
  - sql-injection
links:
  - https://sqlmap.org/
  - https://github.com/sqlmapproject/sqlmap
steps:
  sqlmap_scan:
    name: Scan the remote system
    desc: |
      Scans the remote system to see if its vulnerable to SQL injection and collect information about the system
    commands:
      - sqlmap -u $URL $OPTIONS
    env:
      - name: OPTIONS
        desc: Options used for sqlmap
  sqlmap_dbs:
    name: List databases
    desc: Attempts to retrieve the list of databases
    commands:
      - sqlmap -u $URL $OPTIONS --dbs
    env:
      - name: OPTIONS
        desc: Options used for sqlmap
  sqlmap_tables:
    name: Retrieve tables
    desc: Attempts to retrieve all the tables in the database
    commands:
      - sqlmap -u $URL $OPTIONS --tables -D $DATABASE
    env:
      - name: OPTIONS
        desc: Options used for sqlmap
      - name: DATABASE
        desc: Database name which should be used to retrieve tables
  sqlmap_dump:
    name: Extract data from tables
    desc: Attempts to extract data from a table
    commands:
      - sqlmap -u $URL $OPTIONS --dump -D $DATABASE -T $TABLE
    env:
      - name: OPTIONS
        desc: Options used for sqlmap
      - name: DATABASE
        desc: Database name which should be used to retrieve tables
      - name: TABLE
        desc: Table name which should be used to extract data
