version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    command: '--hostname=0.0.0.0 --mnemonic "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" --db "./"'
    ports:
      - "8545:8545"

  truffle:
    build: blockchain
    command:  sh -c './setup.sh'
    links:
     - ganache

  web-api:
    build: web-api
    ports:
     - "3000:3000"
    command: sh -c './wait-for-ganache.sh -t 80 172.18.0.3:8000 -- npm start'
    depends_on:
     - truffle
    links:
     - truffle
    
