version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - n 16.14.2
      - docker-compose -f docker-compose.aws.yml up -d db
      - yarn install
      - yarn build:backend
      - yarn workspace @gradejs-public/web build
      - yarn workspace @gradejs-public/shared migration:run
      - yarn test
      - docker-compose -f docker-compose.aws.yml down --volumes
      - bash ./cli/archive_artifacts.sh
artifacts:
  files:
    - build.tar
    - .platform/**/*
