version: '3.7'

services:
  db:
    restart: unless-stopped
    image: public.ecr.aws/ubuntu/postgres:latest
    environment:
      POSTGRES_DB: 'gradejs-public'
      POSTGRES_USER: 'gradejs'
      POSTGRES_PASSWORD: 'gradejs'
    ports:
      - '5432:5432'
